d3/index: Avoid highlight errors for non-regexp colors
The "other failures", pending, and success colors don't have regexps,
so hovering over them resulted in:

  TypeError: regexp is undefined

with this commit, we skip highlighting for those colors instead of
erroring out.